baseURL = "/"
title = "SMILEGEN"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"
#googleAnalytics = "G-XXXXXXXXXX"

[params]
fancyTitle = "Smilegen" # title for frontpage, may include image
copyright = ""
description = 'Deliver fast and reliable real-time Invisalign leads.'
startbuttonText = "Contact Us"
startbuttonLink = "#contact"
body_is_markdown = true
#custom_css = "foo.css"
#custom_sass = "bar.scss"
images = ["img/pexels-cedric-fauntleroy-4269363.jpg"]
img = "img/pexels-cedric-fauntleroy-4269363.jpg"

[[params.menu.main]]
url = '/'
title = "Home"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Accelerate Your Invisalign Success<br /> with Swift, Dependable Leads.'
body = '''
Unlock your practice's potential with targeted lead generation that brings in   
qualified clients, ensuring your Invisalign services thrive.
'''

[params.two]
enable = true

[[params.two.section]]
img = "images/img-1.jpg"
img_alt = "invisalign-lead-generation"
title = 'Your Trusted Partner in <br />Lead Generation'
body = 'Rely on our expertise and proven track record to deliver high-quality leads that convert.'

[[params.two.section]]
img = "images/img-5.jpg"
img_alt = "invisalign-lead-generation"
title = 'Driving Your Invisalign<br /> Success'
body = 'Harness the power of our targeted strategies to achieve unparalleled growth and client satisfaction.'

[[params.two.section]]
img = "images/img-4.jpg"
img_alt = "invisalign-lead-generation"
title = 'Empowering Your Practice with<br /> Digital Precision'
body = 'Leverage advanced digital tools and data-driven insights to connect with your ideal Invisalign clients.'

[params.contact]
enable = true
title = "Contact"
body = "Leave us a message."
subject = "New Submission!"
formspree_form_id = "mnnajwyr"

[params.social]
twitter = ""
mastodon = ""
github = ""
facebook = ""
youtube = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"
