[build]
  base    = "."
  publish = "public"
  command = "hugo"

[context.production]
  command = "hugo -F"

[context.production.environment]
  HUGO_VERSION = "0.36"

[context.branch-deploy]
  command = "hugo -D -F"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.36"